# Numpy Giriş

In [1]:
a = [1,2,3]
b= [4,5,6]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[4, 10, 18]

In [2]:
import numpy as np

a = np.array([7,5,8,9])
b = np.array([2,3,6,1])
a * b 

array([14, 15, 48,  9])

In [4]:
x =9

In [5]:
who 

a	 ab	 b	 i	 np	 x	 


In [6]:
x

9

In [9]:
L = [1,2,"f",1.2]
L

[1, 2, 'f', 1.2]

In [10]:
[type(i) for i in L]

[int, int, str, float]

# Numpy Arrayleri Oluşturma

## Listelerden Array Oluşturmak

In [13]:
import numpy as np 
np.array([4,5,6,7])

a = np.array([74,75,72])

a

type(a)

numpy.ndarray

In [14]:
np.array([3.14,4.18,13.34])

array([ 3.14,  4.18, 13.34])

In [18]:
np.array([3.14,4.1813.34], dtype = 'float32')

array([ 3.14,  4.18, 13.34], dtype=float32)

In [19]:
np.zeros(10,dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [24]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [26]:
np.random.normal(0,1,(3,4))

array([[ 0.14401549,  0.87017233, -0.0738647 ,  0.57199746],
       [ 0.76072729,  0.44323816, -0.55029093,  0.07685532],
       [-0.59801345,  1.23987945,  0.03817652, -0.8404693 ]])

In [27]:
np.random.randint(0,10,(2,2))

array([[9, 8],
       [1, 1]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Biçimlendirme

* **ndim** : boyut sayısı
* **shape** : boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri tipi

In [30]:
import numpy as np
a = np.random.randint(10,size = 10)
a.ndim
a.shape
a.size
a.dtype

10

In [36]:
a = np.random.randint(10,size = (10,5))
a

array([[1, 3, 1, 8, 0],
       [5, 5, 9, 7, 6],
       [2, 5, 9, 8, 3],
       [9, 1, 5, 9, 2],
       [0, 4, 2, 3, 5],
       [4, 8, 1, 0, 1],
       [1, 4, 9, 6, 8],
       [2, 8, 1, 9, 2],
       [3, 6, 7, 9, 8],
       [8, 2, 6, 8, 6]])

In [34]:
a.ndim

2

In [35]:
a.shape

(10, 5)

In [37]:
a.size

50

In [38]:
a.dtype

dtype('int32')

In [45]:
a = np.random.randint(10,size = (10,5,7))
a

array([[[2, 8, 5, 5, 4, 4, 8],
        [6, 2, 2, 2, 6, 6, 4],
        [3, 4, 9, 1, 5, 6, 2],
        [9, 7, 8, 4, 9, 2, 7],
        [1, 5, 7, 3, 5, 4, 7]],

       [[6, 3, 6, 3, 8, 6, 2],
        [5, 6, 4, 3, 6, 5, 2],
        [5, 2, 9, 2, 9, 4, 3],
        [7, 9, 2, 9, 0, 0, 7],
        [1, 3, 3, 4, 0, 5, 6]],

       [[5, 7, 3, 6, 5, 9, 5],
        [7, 4, 7, 2, 6, 4, 6],
        [7, 9, 3, 2, 6, 2, 9],
        [4, 4, 1, 5, 4, 1, 7],
        [6, 8, 5, 7, 7, 6, 7]],

       [[4, 6, 8, 0, 8, 6, 2],
        [2, 7, 8, 9, 9, 7, 3],
        [7, 1, 7, 8, 4, 9, 9],
        [5, 7, 6, 2, 8, 8, 1],
        [0, 3, 7, 3, 8, 8, 0]],

       [[8, 6, 1, 3, 5, 9, 9],
        [1, 8, 5, 5, 8, 6, 2],
        [3, 0, 6, 4, 0, 8, 4],
        [0, 7, 1, 3, 7, 1, 3],
        [1, 6, 4, 3, 4, 3, 1]],

       [[0, 9, 5, 4, 3, 9, 9],
        [8, 3, 7, 0, 0, 8, 6],
        [7, 8, 4, 5, 4, 2, 1],
        [6, 2, 3, 5, 9, 1, 6],
        [2, 4, 7, 1, 0, 4, 9]],

       [[6, 6, 2, 7, 3, 5, 4],
        [0, 6, 2, 6, 8, 4, 

In [46]:
a.ndim

3

In [47]:
a.shape

(10, 5, 7)

In [48]:
a.size

350

In [49]:
a.dtype

dtype('int32')

In [52]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [60]:
b = a.reshape((1,3))

In [61]:
b.ndim

2

In [62]:
a[np.newaxis,:]

array([[1, 2, 3]])

In [63]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Array Birleştirme İşlemleri

In [64]:
x = np.array([8,9,10])
y = np.array([12,14,15])

In [65]:
x

array([ 8,  9, 10])

In [66]:
y

array([12, 14, 15])

## Tek Boyutlu Array

In [67]:
np.concatenate([x,y])

array([ 8,  9, 10, 12, 14, 15])

In [68]:
z = [20,10,30]

In [69]:
np.concatenate([x,y,z])

array([ 8,  9, 10, 12, 14, 15, 20, 10, 30])

## İki Boyutlu Array

In [71]:
f = np.array([[5,6,8],
             [84,95,61]])
f

array([[ 5,  6,  8],
       [84, 95, 61]])

In [72]:
np.concatenate([f,f])

array([[ 5,  6,  8],
       [84, 95, 61],
       [ 5,  6,  8],
       [84, 95, 61]])

In [73]:
np.concatenate([f,f], axis = 1)

array([[ 5,  6,  8,  5,  6,  8],
       [84, 95, 61, 84, 95, 61]])

## Farklı Boyutlu Array

In [109]:
f = np.array([1,2,3])

z = np.array([[7,8,9],
              [5,4,3]])

In [110]:
np.vstack([f,z])

array([[1, 2, 3],
       [7, 8, 9],
       [5, 4, 3]])

In [87]:
 z = np.array([[99],
              [99]])

In [88]:
z

array([[99],
       [99]])

In [104]:
 e = np.array([[79],
              [93]])

In [105]:
e

array([[79],
       [93]])

In [106]:
np.hstack((e,z))

array([[79, 99],
       [93, 99]])

# Array Ayırma Splitting

In [220]:
e = [1,2,3,4,5,6,7,8,9,10,11,12]
e

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [226]:
np.split(e,[3,7,10])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10]), array([11, 12])]

In [224]:
z,r,s = np.split(e,[3,5])

In [124]:
z

array([1, 2, 3])

In [125]:
r

array([4, 5])

In [126]:
s

array([6, 7, 8, 9])

In [228]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [229]:
ust,alt = np.vsplit(m,[2])

In [230]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [134]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [143]:
sag, sol = np.hsplit(m,[2])

In [144]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [145]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

 # Array Sıralama
 

In [159]:
v = np.array([5,8,96,3]) 
v

array([ 5,  8, 96,  3])

In [160]:
np.sort(v)

array([ 3,  5,  8, 96])

In [161]:
v

array([ 5,  8, 96,  3])

In [162]:
v.sort()

In [163]:
v

array([ 3,  5,  8, 96])

In [164]:
e = np.array([1997,1961,1959,1989,1992])

In [173]:
np.sort(e)

array([1959, 1961, 1989, 1992, 1997])

In [176]:
i = np.argsort(e) #Yapılan sıralama sonrası yeri değişen indekslerin yeni yerlerini gösterir

In [178]:
i

array([2, 1, 3, 4, 0], dtype=int64)

In [179]:
e

array([1997, 1961, 1959, 1989, 1992])

In [182]:
e[i] # değişmiş halinin değerlerini gösterir

array([1959, 1961, 1989, 1992, 1997])

In [183]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

# Numpy Eleman İşlemleri

In [186]:
import numpy as np 
a = np.random.randint(10,size = 10)
a

array([8, 0, 2, 8, 8, 8, 4, 7, 5, 6])

In [195]:
s = np.random.randint(20,size = (3,5))
s

array([[ 4, 17, 13,  3, 19],
       [ 8, 11, 14, 13, 13],
       [ 8, 19,  5,  7, 18]])

In [199]:
s[0][4]

19

In [200]:
s[2,4]

18

In [203]:
s[2][3]

7

In [204]:
s[2][3] = 9
s

array([[ 4, 17, 13,  3, 19],
       [ 8, 11, 14, 13, 13],
       [ 8, 19,  5,  9, 18]])

In [193]:
r = np.random.randint(30,size = (4,5,8))
r

array([[[ 2,  8, 25, 14,  5, 11,  8, 21],
        [27, 25,  6, 29, 15, 10, 16,  5],
        [19,  8, 20, 13, 25,  3,  3, 23],
        [ 3, 13, 15, 28, 24,  4,  9, 18],
        [25, 21, 20, 26,  9, 13, 23,  5]],

       [[ 6, 26, 15,  6,  0, 29,  8, 13],
        [27, 16, 17,  1,  4,  1, 25, 28],
        [10, 16,  4,  0,  1,  7,  1,  3],
        [27, 15,  0, 15, 21, 28, 15, 16],
        [ 2, 25,  3, 27, 22,  5,  8,  4]],

       [[ 6,  8, 19,  6, 17, 16,  6, 11],
        [25, 11,  1,  7, 29, 26, 19,  4],
        [16, 20, 11, 19, 10,  3,  1, 21],
        [ 2,  4,  8,  3, 26,  7, 18,  0],
        [16,  8, 23, 29, 18, 15, 17,  1]],

       [[ 1, 24, 10,  3,  3, 28,  4, 19],
        [25, 17,  4,  5, 16, 14, 24, 27],
        [17, 26, 15, 28, 12, 16, 25, 16],
        [ 9, 25,  8, 22, 10,  4,  9, 13],
        [ 6, 12, 28,  5, 25, 15,  8, 10]]])

In [213]:
r[0,4,6] = 5.2
r[0][4][6]

5

# Slicing ile Array Alt Kümesine Erişmek

In [215]:
e = np.arange(20,30)
e

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [216]:
e[0:3]

array([20, 21, 22])

In [231]:
e[:3]

[1, 2, 3]

In [232]:
e[3:] # 3 ten sonraki sayıları yazdır

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [233]:
e[::2] #1 den başlayarak 2 adım atlayarak git

[1, 3, 5, 7, 9, 11]

In [234]:
e[1::2] # 1 dahil değil 2 sayı atlayarak git

[2, 4, 6, 8, 10, 12]

In [236]:
z = np.random.randint(10,size = (5,5))
z

array([[9, 5, 5, 6, 8],
       [9, 5, 8, 3, 9],
       [5, 0, 8, 4, 1],
       [4, 4, 9, 7, 5],
       [2, 3, 7, 3, 1]])

In [238]:
z[:,0] #0. sütun

array([9, 9, 5, 4, 2])

In [239]:
z[0,:]# 0.satır

array([9, 5, 5, 6, 8])

In [240]:
z[1,:] # 1.satır

array([9, 5, 8, 3, 9])

In [241]:
z[:,1] # 1.sütun

array([5, 5, 0, 4, 3])

In [242]:
z[3,2]

9

In [243]:
z[0]

array([9, 5, 5, 6, 8])

In [247]:
z[0:2,0:3]

array([[9, 5, 5],
       [9, 5, 8]])

In [249]:
z[::,:3]

array([[9, 5, 5],
       [9, 5, 8],
       [5, 0, 8],
       [4, 4, 9],
       [2, 3, 7]])

In [252]:
z[:,:2]

array([[9, 5],
       [9, 5],
       [5, 0],
       [4, 4],
       [2, 3]])

In [264]:
s = np.random.randint(10,size = (8,8))
s

array([[6, 7, 2, 5, 7, 9, 4, 2],
       [2, 2, 1, 7, 6, 5, 8, 9],
       [5, 5, 3, 8, 6, 1, 4, 9],
       [0, 7, 2, 1, 0, 0, 3, 8],
       [6, 3, 3, 0, 2, 0, 0, 0],
       [7, 4, 4, 9, 0, 1, 8, 3],
       [0, 6, 6, 6, 5, 7, 3, 6],
       [4, 8, 5, 4, 7, 1, 4, 5]])

In [255]:
alt_s = s[0:3,0:2]

In [256]:
alt_s

array([[7, 6],
       [6, 5],
       [8, 0]])

In [257]:
alt_s[0,0] = 99

In [258]:
alt_s

array([[99,  6],
       [ 6,  5],
       [ 8,  0]])

In [265]:
alt_b = s[0:3,0:2].copy()

In [266]:
alt_b

array([[6, 7],
       [2, 2],
       [5, 5]])

In [267]:
s

array([[6, 7, 2, 5, 7, 9, 4, 2],
       [2, 2, 1, 7, 6, 5, 8, 9],
       [5, 5, 3, 8, 6, 1, 4, 9],
       [0, 7, 2, 1, 0, 0, 3, 8],
       [6, 3, 3, 0, 2, 0, 0, 0],
       [7, 4, 4, 9, 0, 1, 8, 3],
       [0, 6, 6, 6, 5, 7, 3, 6],
       [4, 8, 5, 4, 7, 1, 4, 5]])

# Fancy Index ile Eleman İşlemleri

In [285]:
r = np.arange(0,30,3)
r

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [269]:
r[1]

3

In [270]:
r[5]

15

In [271]:
[r[2],r[6]]

[6, 18]

In [276]:
al_getir = [4,6,8]

In [278]:
r[al_getir] # al_getir vektörünün içine girdi. içindeki elemanlara baktı. Sonra r nin içinde al_getir değeri kadar ilerletip o değeri ekrana yazdırır

array([12, 18, 24])

In [288]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [289]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [290]:
m[satir, sutun]

array([1, 5])

In [294]:
m[0,[1,1]]

array([1, 1])

In [299]:
m[0:,[0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [300]:
h = np.arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [301]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [303]:
h[index] = 99

In [304]:
h

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [307]:
h[[0,1]] = [4,6]

In [308]:
h

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

# Koşullu Elaman İşlemleri

In [309]:
f = np.array([1,2,3,4,5,6])

In [310]:
f > 3

array([False, False, False,  True,  True,  True])

In [311]:
f < 3

array([ True,  True, False, False, False, False])

In [312]:
f == 3

array([False, False,  True, False, False, False])

In [313]:
f != 3 

array([ True,  True, False,  True,  True,  True])

In [314]:
(2 * f)

array([ 2,  4,  6,  8, 10, 12])

In [315]:
(f ** 2 )

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [316]:
(2 * v) == (v ** 2)

array([False, False, False, False])

In [ ]:
## ufunc => vektör düzeyinde döngü yazmadan karşılaştırma yapılmasını sağlar

np.equal - eşitlik kontrolü
np.not_equal - eşitsizlik kontrolü
np.less 
np.less_equal
np.greater
np.greater_equal

In [317]:
v = np.array([2,5,6,9,3])

In [318]:
np.equal(3,v)

array([False, False, False, False,  True])

In [320]:
np.equal([0,2,3], np.arange(3))

array([ True, False, False])

In [321]:
np.arange(3)

array([0, 1, 2])

In [323]:
g = np.random.randint(0,10,(3,3))
g

array([[6, 2, 8],
       [5, 8, 5],
       [6, 5, 5]])

In [324]:
g > 5

array([[ True, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [325]:
np.sum(g>5)

4

In [327]:
(g > 5) & (g < 7)

array([[ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [328]:
np.sum((g > 3) | ( g < 7) )

9

In [329]:
np.sum(g > 4, axis =1) # satır bazında karşılaştırma

array([2, 3, 3])

In [330]:
np.sum(g > 4, axis =0) # sutun bazında karşılaştırma

array([3, 2, 3])

In [331]:
np.all(g > 4) # vektördeki tüm değeler 4 ten büyük mü? 

False

In [332]:
np.all(g > 0)

True

In [333]:
np.any(g > 4) # vektörde 4 ten büyük  değer var mı? 

True

In [334]:
np.all(g > 4, axis = 0)

array([ True, False,  True])

In [335]:
np.all(g > 4, axis = 1)

array([False,  True,  True])

In [336]:
n = np.array([5,8,9,6,3,6,7])
n

array([5, 8, 9, 6, 3, 6, 7])

In [337]:
n[0]

5

In [338]:
n > 3

array([ True,  True,  True,  True, False,  True,  True])

In [339]:
n[n > 3] # köşeli parantezin içindeki koşulu sağlayan değerler getirilir.

array([5, 8, 9, 6, 6, 7])

In [342]:
n[(n > 1) & (n < 5)]

array([3])

# NumPy Hesaplamalı İşlemler


In [3]:
import numpy as np
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
e - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [5]:
e / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
e * 5 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
e ** 2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [8]:
e / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
8* (a *3 * 5)

array([ 840,  600,  960, 1080])

In [14]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.add(e,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.subtract(e,1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [19]:
np.multiply(e,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [20]:
np.divide(e,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [21]:
np.power(e,9)

array([        0,         1,       512,     19683,    262144,   1953125,
        10077696,  40353607, 134217728, 387420489], dtype=int32)

In [22]:
p = np.arange(1,9)
p

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.add.reduce(p)

36

In [26]:
np.add.accumulate(p)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [31]:
p = np.random.normal(0,1,30)
p

array([-0.21482919, -0.81743999,  0.99284812,  0.98888023, -1.62608583,
        1.84070747, -0.14255991, -0.50364796,  1.57685321,  0.07649779,
        0.78704897, -0.25879246,  1.64318482,  1.11572602, -0.54056944,
       -0.87086311, -0.33011301, -1.12829499,  1.46207959,  1.34794619,
        0.17032121,  1.48226123,  1.07362001,  0.8146094 ,  0.01423832,
        0.0695307 ,  0.4609796 ,  0.3450701 , -0.41140439,  0.00979032])

In [29]:
np.mean(p) # aritmetik ortalama

-0.004537074437153255

In [32]:
np.std(p) #standart sapma

0.8959337601269487

In [35]:
np.var(p) #varyans

0.8026973025352128

In [36]:
np.median(p)#medyan

0.12340950000330861

In [37]:
sum(p) #toplama

9.427593028861446

In [38]:
a = np.random.normal(0,1,(3,3))
a

array([[ 1.05702708, -1.21685328, -1.97039638],
       [ 0.98627788, -0.27490902, -0.84741421],
       [-0.90555684, -0.67635283, -0.53181206]])

In [39]:
a.sum()

-4.37998966090738

In [40]:
a.sum(axis =0)#satır bazında toplama

array([ 1.13774812, -2.16811513, -3.34962265])

In [41]:
a.sum(axis = 1) #sütun bazında toplama

array([-2.13022258, -0.13604535, -2.11372173])

# Farklı Boyutlu Arrayler ile Birlikte Çalışmak(broadcasting)

In [43]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1,2,3])

a+b

array([2, 4, 6])

In [45]:
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a+m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [47]:
b = np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [49]:
a

array([1, 2, 3])

In [48]:
a+b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [50]:
r = np.arange(3).reshape((3,1))
r

array([[0],
       [1],
       [2]])

In [51]:
b = np.arange(3)
b

array([0, 1, 2])

In [53]:
r.shape

(3, 1)

In [54]:
b.shape

(3,)

In [56]:
b+r

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [100]:
y = np.arange(12).reshape((6,2))
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [101]:
t = np.arange(2)
t

array([0, 1])

In [102]:
y+t

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10],
       [10, 12]])

In [104]:
n = np.ones((3,2))
n

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [106]:
s = np.arange(2)
s

array([0, 1])

In [107]:
s+ n

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

# Numpy Yapısal Array'ler

** Hello good bye numpy

In [108]:
isim = ['zeynep','emin','reyhan','şüheda']
yas = [59,61,28,31]
boy = [1.55,1.70,1.63,1.55]


In [114]:
data = np.zeros(4,dtype= {'names': ('isim','yas','boy'),
                          'formats': ('U10','i4','f8')})

In [115]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [116]:
data['isim'] = isim
data['yas'] = yas
data['boy'] = boy

In [118]:
data

array([('zeynep', 59, 1.55), ('emin', 61, 1.7 ), ('reyhan', 28, 1.63),
       ('şüheda', 31, 1.55)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [119]:
data['isim']

array(['zeynep', 'emin', 'reyhan', 'şüheda'], dtype='<U10')

In [120]:
data[0]

('zeynep', 59, 1.55)

In [121]:
data[data['yas'] < 40]['isim']

array(['reyhan', 'şüheda'], dtype='<U10')

# Pandas

## Pandas Series

In [2]:
import numpy as np
import pandas as pd

In [4]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
seri = pd.Series([2,5,8,9,6])

In [7]:
type(seri)

pandas.core.series.Series

In [8]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [10]:
seri.dtype 

dtype('int64')

In [11]:
seri.empty

False

In [12]:
seri.ndim

1

In [13]:
seri.size

5

In [15]:
seri.values

array([2, 5, 8, 9, 6], dtype=int64)

In [16]:
seri.head(2)# baştan 2 eleman göster

0    2
1    5
dtype: int64

In [17]:
seri[0:3]  #slicing ile 0. indeksten  3. indekse kadar olan elemaları göster

0    2
1    5
2    8
dtype: int64

In [18]:
seri.tail(2)  # sondan 2 eleman göster

3    9
4    6
dtype: int64

In [19]:
f= np.array([4,8,9,6,3])
f

array([4, 8, 9, 6, 3])

In [20]:
type(f)

numpy.ndarray

In [21]:
seri = pd.Series(f)

In [22]:
seri

0    4
1    8
2    9
3    6
4    3
dtype: int32

In [23]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [24]:
seri[0]

4

In [26]:
seri = pd.Series([8,9,6,1,10], index = ['e','z','ş','r','f'])

In [27]:
seri['e']

8

In [28]:
sozluk = {"reg" : 10, "loj": 11, "cart": 12 }

In [29]:
sozluk

{'reg': 10, 'loj': 11, 'cart': 12}

In [30]:
seri = pd.Series(sozluk)

In [31]:
seri["reg"]

10

In [34]:
seri["loj":"cart"]

loj     11
cart    12
dtype: int64

In [35]:
pd.concat([seri,seri])

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [36]:
seri.append(seri)

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [37]:
seri

reg     10
loj     11
cart    12
dtype: int64

# Serilerde Eleman İşlemleri

In [38]:
s = np.array([1,2,3,4,5])
seri = pd.Series(s)
seri

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [40]:
seri[0]

1

In [41]:
seri[0:3]

0    1
1    2
2    3
dtype: int32

In [44]:
seri = pd.Series([10,11,12,13],
                 index = ['reg','loj','cart','rf'])

seri 

reg     10
loj     11
cart    12
rf      13
dtype: int64

In [45]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [46]:
seri.keys

<bound method Series.keys of reg     10
loj     11
cart    12
rf      13
dtype: int64>

In [47]:
list(seri.items())

[('reg', 10), ('loj', 11), ('cart', 12), ('rf', 13)]

In [48]:
seri.values

array([10, 11, 12, 13], dtype=int64)

In [50]:
seri

reg     10
loj     11
cart    12
rf      13
dtype: int64

In [51]:
"knn" in seri

False

In [52]:
"reg" in seri

True

In [53]:
seri["reg"]

10

In [54]:
seri[['rf','reg']]

rf     13
reg    10
dtype: int64

In [55]:
seri["rf"] = 125

In [56]:
seri

reg      10
loj      11
cart     12
rf      125
dtype: int64

In [57]:
seri['loj': 'rf']

loj      11
cart     12
rf      125
dtype: int64

In [58]:
seri = pd.Series([121,200,150,99], index = ["reg","loj","cart","rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [59]:
seri[(seri > 125) & (seri < 350)]

loj     200
cart    150
dtype: int64

In [61]:
data = pd.Series(['a','b','c'],index = [1,2,3])
data

1    a
2    b
3    c
dtype: object

In [62]:
data[1]

'a'

In [63]:
data[1:3]

2    b
3    c
dtype: object

In [64]:
data[0:3]

1    a
2    b
3    c
dtype: object

In [65]:
# loc label based indexing, tanımlandığı şekli ile index yakalamak

In [66]:
data

1    a
2    b
3    c
dtype: object

In [67]:
data.loc[1]

'a'

In [69]:
data.loc[3]

'c'

In [71]:
data.loc[0:5]

1    a
2    b
3    c
dtype: object

In [72]:
# iloc positional indexing, indexi sıfırlayarak yakalamak

In [73]:
data

1    a
2    b
3    c
dtype: object

In [74]:
data.iloc[2]

'c'

In [75]:
data.iloc[0:3]

1    a
2    b
3    c
dtype: object

# Pandas DataFrame Özellikleri & Oluşturma 

In [76]:
l = [1,5,6,9]
l

[1, 5, 6, 9]

In [79]:
pd.DataFrame(l,columns = ['degisken_ismi'])

degisken_ismi
0              1
1              5
2              6
3              9

In [80]:
df = pd.DataFrame(l,columns = ['degisken_ismi'])

In [81]:
type(df)

pandas.core.frame.DataFrame

In [83]:
df.axes #içeriği

[RangeIndex(start=0, stop=4, step=1), Index(['degisken_ismi'], dtype='object')]

In [84]:
df.shape

(4, 1)

In [85]:
df.ndim

2

In [86]:
df.size

4

In [87]:
df.values

array([[1],
       [5],
       [6],
       [9]], dtype=int64)

In [88]:
df.head(2)

degisken_ismi
0              1
1              5

In [89]:
df.tail(2)

degisken_ismi
2              6
3              9

In [90]:
f = np.array([1,2,3,4,5,6])

In [91]:
pd.DataFrame(f,columns = ['degisken_ismi'])

degisken_ismi
0              1
1              2
2              3
3              4
4              5
5              6

In [96]:
m = np.arange(1,10).reshape((3,3))

In [97]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
pd.DataFrame(m,columns = ['var1','var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [99]:
df =pd.DataFrame(m,columns = ['var1','var2','var3'])

In [100]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [101]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [102]:
df.columns = ('deg1','deg2','deg3')

In [103]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [104]:
pd.DataFrame(m,columns = ['deg1','deg2','deg3'], index = ['a','b','c'])

deg1  deg2  deg3
a     1     2     3
b     4     5     6
c     7     8     9

In [105]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

 # DataFrame Eleman İşlemleri 

In [3]:
import numpy as np
import pandas as pd

s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10,size = 5)

df = pd.DataFrame({ "var1" : s1 , "var2": s2, "var3": s3})
df

var1  var2  var3
0     5     0     3
1     4     0     8
2     9     8     9
3     2     1     5
4     7     3     2

In [4]:
df[0:1]

var1  var2  var3
0     5     0     3

In [5]:
df.index = ['a','b','c','d','e']

In [6]:
df

var1  var2  var3
a     5     0     3
b     4     0     8
c     9     8     9
d     2     1     5
e     7     3     2

In [7]:
df['c':'e']

var1  var2  var3
c     9     8     9
d     2     1     5
e     7     3     2

In [8]:
df.drop('a',axis =0)

var1  var2  var3
b     4     0     8
c     9     8     9
d     2     1     5
e     7     3     2

In [9]:
df

var1  var2  var3
a     5     0     3
b     4     0     8
c     9     8     9
d     2     1     5
e     7     3     2

In [10]:
df.drop('a',axis=0,inplace= True)

In [11]:
df

var1  var2  var3
b     4     0     8
c     9     8     9
d     2     1     5
e     7     3     2

In [26]:
l = ['b','e']

In [27]:
df.drop(l, axis =0)

var1  var2  var3
c     9     8     9
d     2     1     5

In [28]:
df

var1  var2  var3
b     4     0     8
c     9     8     9
d     2     1     5
e     7     3     2

In [29]:
'var1' in df

True

In [30]:
l = ['var1','var2', 'var3']

In [31]:
for i in l :
    print(i in df)

True
True
True


In [32]:
df['var1'] is df['var1']

True

In [33]:
df['var2']

b    0
c    8
d    1
e    3
Name: var2, dtype: int32

In [34]:
df.var1

b    4
c    9
d    2
e    7
Name: var1, dtype: int32

In [35]:
df[['var1', 'var2']]

var1  var2
b     4     0
c     9     8
d     2     1
e     7     3

In [36]:
l = ['var1', 'var2']

In [37]:
df

var1  var2  var3
b     4     0     8
c     9     8     9
d     2     1     5
e     7     3     2

In [38]:
df[l]

var1  var2
b     4     0
c     9     8
d     2     1
e     7     3

In [42]:
 df['var4'] = [5,8,9,6]

In [43]:
df

var1  var2  var3  var4
b     4     0     8     5
c     9     8     9     8
d     2     1     5     9
e     7     3     2     6

In [44]:
df['var5'] = df['var1'] / df['var2']

In [45]:
df

var1  var2  var3  var4      var5
b     4     0     8     5       inf
c     9     8     9     8  1.125000
d     2     1     5     9  2.000000
e     7     3     2     6  2.333333

In [46]:
df.drop('var5', axis = 1)

var1  var2  var3  var4
b     4     0     8     5
c     9     8     9     8
d     2     1     5     9
e     7     3     2     6

In [48]:
df

var1  var2  var3  var4      var5
b     4     0     8     5       inf
c     9     8     9     8  1.125000
d     2     1     5     9  2.000000
e     7     3     2     6  2.333333

In [49]:
df.drop('var5', axis = 1 , inplace = True)

In [50]:
df

var1  var2  var3  var4
b     4     0     8     5
c     9     8     9     8
d     2     1     5     9
e     7     3     2     6

In [51]:
l

['var1', 'var2']

In [53]:
df.drop(l,axis = 1)

var3  var4
b     8     5
c     9     8
d     5     9
e     2     6

In [54]:
df

var1  var2  var3  var4
b     4     0     8     5
c     9     8     9     8
d     2     1     5     9
e     7     3     2     6

# Gözlem ve Değişkenlere Birlikte Erişmek

In [58]:
import numpy as np
import pandas as pd

s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10,size = 5)
df = pd.DataFrame({"var1": s1, "var2": s2, "var3": s3})
df

var1  var2  var3
0     6     2     4
1     5     0     1
2     2     6     3
3     4     9     3
4     2     9     8

In [60]:
df.iloc[0:3]

var1  var2  var3
0     6     2     4
1     5     0     1
2     2     6     3

In [61]:
df.iloc[0,0]

6

In [64]:
df.iloc[2,2]

3

In [65]:
df.iloc[:3,:2]

var1  var2
0     6     2
1     5     0
2     2     6

In [66]:
df.loc[:3:2]

var1  var2  var3
0     6     2     4
2     2     6     3

In [67]:
df.iloc[2:6,1:3]

var2  var3
2     6     3
3     9     3
4     9     8

In [68]:
df.loc[0:3,'var3']

0    4
1    1
2    3
3    3
Name: var3, dtype: int32

In [70]:
 df.loc[0:3,'var2':'var3']

var2  var3
0     2     4
1     0     1
2     6     3
3     9     3

In [71]:
df.iloc[0:3,1:3]

var2  var3
0     2     4
1     0     1
2     6     3

In [73]:
df.index = ['a','b','c','d','e']

In [74]:
df

var1  var2  var3
a     6     2     4
b     5     0     1
c     2     6     3
d     4     9     3
e     2     9     8

In [75]:
df.loc["c":"d", "var1":"var3"]

var1  var2  var3
c     2     6     3
d     4     9     3

In [76]:
df[df.var1 > 5]['var2']

a    2
Name: var2, dtype: int32

In [80]:
df[(df.var1 > 2) & (df.var3 > 2)]

var1  var2  var3
a     6     2     4
d     4     9     3

In [82]:
df.loc[(df.var1 > 3) & (df.var3 > 2)]["var3"]

a    4
d    3
Name: var3, dtype: int32

In [91]:
df.loc[df.var1 > 5,['var2','var1']]

var2  var1
a     2     6

In [92]:
df

var1  var2  var3
a     6     2     4
b     5     0     1
c     2     6     3
d     4     9     3
e     2     9     8

# BİRLEŞTİRME (JOIN) İŞLEMLERİ

In [2]:
import numpy as np
import pandas as pd

s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10, size = 5)
df1 = pd.DataFrame({"var1": s1, "var2":s2, "var3": s3})
df1

var1  var2  var3
0     4     4     8
1     0     3     0
2     3     4     0
3     4     0     4
4     5     5     2

In [4]:
df2 = df1 + 99
df2

var1  var2  var3
0   103   103   107
1    99   102    99
2   102   103    99
3   103    99   103
4   104   104   101

In [5]:
pd.concat([df1,df2],axis = 1 )

var1  var2  var3  var1  var2  var3
0     8     3     5   107   102   104
1     3     7     9   102   106   108
2     7     8     4   106   107   103
3     4     6     3   103   105   102
4     3     5     0   102   104    99

In [6]:
pd.concat([df1,df2],ignore_index = True)

var1  var2  var3
0     8     3     5
1     3     7     9
2     7     8     4
3     4     6     3
4     3     5     0
5   107   102   104
6   102   106   108
7   106   107   103
8   103   105   102
9   102   104    99

In [7]:
pd.concat([df1,df2],ignore_index = True, axis = 1 )

0  1  2    3    4    5
0  8  3  5  107  102  104
1  3  7  9  102  106  108
2  7  8  4  106  107  103
3  4  6  3  103  105  102
4  3  5  0  102  104   99

In [8]:
df1

var1  var2  var3
0     8     3     5
1     3     7     9
2     7     8     4
3     4     6     3
4     3     5     0

In [5]:
pd.concat([df1,df2])

var1  var2  var3
0     4     4     8
1     0     3     0
2     3     4     0
3     4     0     4
4     5     5     2
0   103   103   107
1    99   102    99
2   102   103    99
3   103    99   103
4   104   104   101

In [6]:
pd.concat([df1,df2], join = 'inner')

var1  var2  var3
0     4     4     8
1     0     3     0
2     3     4     0
3     4     0     4
4     5     5     2
0   103   103   107
1    99   102    99
2   102   103    99
3   103    99   103
4   104   104   101

In [8]:
pd.concat([df1,df2], join_axes = [df1.columns])

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [9]:
#merge and join 

In [10]:
df1 = pd.DataFrame({'calisanlar' : ['Veli','Ali','Zehra','Fadime'],
                    'grup' : ['Muhasebe','Muhendislik','Muhendislik','İK']})
df1

calisanlar         grup
0       Veli     Muhasebe
1        Ali  Muhendislik
2      Zehra  Muhendislik
3     Fadime           İK

In [12]:
df2 = pd.DataFrame({'calisanlar' : ['Veli','Ali','Zehra','Fadime'],
                         'ilk_giris': [2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Veli       2010
1        Ali       2009
2      Zehra       2014
3     Fadime       2019

In [13]:
df3 = pd.DataFrame({'grup': ['Muhasebe','Muhendislik','İK'],
                    'müdür': ['Caner','Berkcan','Mustafa']})
df3

grup    müdür
0     Muhasebe    Caner
1  Muhendislik  Berkcan
2           İK  Mustafa

In [14]:
df4 = pd.DataFrame({'grup': ['Muhasebe','Muhendislik','İK','Muhasebe','Muhendislik','İK'],
                    'yetenekler': ['matematik','excel','kodlama','linux','excel','yonetim']})
df4

grup yetenekler
0     Muhasebe  matematik
1  Muhendislik      excel
2           İK    kodlama
3     Muhasebe      linux
4  Muhendislik      excel
5           İK    yonetim

In [15]:
pd.merge(df1,df2)

calisanlar         grup  ilk_giris
0       Veli     Muhasebe       2010
1        Ali  Muhendislik       2009
2      Zehra  Muhendislik       2014
3     Fadime           İK       2019

In [16]:
pd.merge(df1,df2, on='calisanlar')

calisanlar         grup  ilk_giris
0       Veli     Muhasebe       2010
1        Ali  Muhendislik       2009
2      Zehra  Muhendislik       2014
3     Fadime           İK       2019

In [17]:
df5 = pd.merge(df1,df2)

In [18]:
df5

calisanlar         grup  ilk_giris
0       Veli     Muhasebe       2010
1        Ali  Muhendislik       2009
2      Zehra  Muhendislik       2014
3     Fadime           İK       2019

In [19]:
pd.merge(df3,df4)

grup    müdür yetenekler
0     Muhasebe    Caner  matematik
1     Muhasebe    Caner      linux
2  Muhendislik  Berkcan      excel
3  Muhendislik  Berkcan      excel
4           İK  Mustafa    kodlama
5           İK  Mustafa    yonetim

In [21]:
pd.merge(df1,df4)

calisanlar         grup yetenekler
0       Veli     Muhasebe  matematik
1       Veli     Muhasebe      linux
2        Ali  Muhendislik      excel
3        Ali  Muhendislik      excel
4      Zehra  Muhendislik      excel
5      Zehra  Muhendislik      excel
6     Fadime           İK    kodlama
7     Fadime           İK    yonetim

In [22]:
df6 = pd.DataFrame({'name': ['Ali','Veli','Zehra','Burcu'],
                    'maas': [7000,8000,9000,6000]})
df6

name  maas
0    Ali  7000
1   Veli  8000
2  Zehra  9000
3  Burcu  6000

In [23]:
df1

calisanlar         grup
0       Veli     Muhasebe
1        Ali  Muhendislik
2      Zehra  Muhendislik
3     Fadime           İK

In [24]:
pd.merge(df1,df6, left_on='calisanlar',right_on= 'name' )

calisanlar         grup   name  maas
0       Veli     Muhasebe   Veli  8000
1        Ali  Muhendislik    Ali  7000
2      Zehra  Muhendislik  Zehra  9000

In [27]:
pd.merge(df1,df6, left_on='calisanlar', right_on = 'name').drop('name',axis= 1)

calisanlar         grup  maas
0       Veli     Muhasebe  8000
1        Ali  Muhendislik  7000
2      Zehra  Muhendislik  9000

In [51]:
df1

calisanlar         grup
0       Veli     Muhasebe
1        Ali  Muhendislik
2      Zehra  Muhendislik
3     Fadime           İK

In [48]:
df1.shape

(4, 2)

In [53]:
df1a = df1.set_index('calisanlar') #değişken değerlerini gözlem ismi olarak atadık
df1a

grup
calisanlar             
Veli           Muhasebe
Ali         Muhendislik
Zehra       Muhendislik
Fadime               İK

In [54]:
df1a.shape

(4, 1)

In [55]:
df2

calisanlar  ilk_giris
0       Veli       2010
1        Ali       2009
2      Zehra       2014
3     Fadime       2019

In [56]:
df2.shape

(4, 2)

In [59]:
df2a = df2.set_index('calisanlar')
df2a

ilk_giris
calisanlar           
Veli             2010
Ali              2009
Zehra            2014
Fadime           2019

In [60]:
df2a.shape

(4, 1)

In [61]:
pd.merge(df2a,df1a,left_index= True, right_index = True)

ilk_giris         grup
calisanlar                        
Veli             2010     Muhasebe
Ali              2009  Muhendislik
Zehra            2014  Muhendislik
Fadime           2019           İK

In [62]:
df1a.join(df2a)

grup  ilk_giris
calisanlar                        
Veli           Muhasebe       2010
Ali         Muhendislik       2009
Zehra       Muhendislik       2014
Fadime               İK       2019

In [63]:
dfa = pd.DataFrame({'calisanlar': ['Ali','Veli','Aslan'],
                    'siralama': [1,2,3]})

dfa

calisanlar  siralama
0        Ali         1
1       Veli         2
2      Aslan         3

In [65]:
dfb = pd.DataFrame({'calisanlar': ['Ali','Veli','Aslan'],
                    'siralama': [7,20,3]})
dfb

calisanlar  siralama
0        Ali         7
1       Veli        20
2      Aslan        93

In [66]:
pd.merge(dfa,dfb, on= 'calisanlar')

calisanlar  siralama_x  siralama_y
0        Ali           1           7
1       Veli           2          20
2      Aslan           3          93

In [67]:
pd.merge(dfa,dfb,on= 'calisanlar', suffixes = ["_MAAS","_DENEYIM"] )

calisanlar  siralama_MAAS  siralama_DENEYIM
0        Ali              1                 7
1       Veli              2                20
2      Aslan              3                93

# Gruplama İşlemleri

In [69]:
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                   'veri': [10,50,60,80,90,40]}, columns = ['gruplar','veri'])
df

gruplar  veri
0       A    10
1       B    50
2       C    60
3       A    80
4       B    90
5       C    40

In [70]:
df.groupby('gruplar')

In [71]:
df.groupby('gruplar').sum()

veri
gruplar      
A          90
B         140
C         100

In [22]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [24]:
df.groupby('method')['orbital_period']

In [25]:
df.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [27]:
df.groupby('method')['orbital_period'].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

## Basit Toplulaştırma Fonksiyonları:

* **count()**
* **first()**
* **last()**
* **mean()**
* **median()**
* **min()**
* **max()**
* **std()**
* **var()**
* **sum()**


In [3]:
import seaborn as sns 

In [4]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load a dataset from the online repository (requires internet).

Parameters
----------
name : str
    Name of the dataset (`name`.csv on
    https://github.com/mwaskom/seaborn-data).  You can obtain list of
    available datasets using :func:`get_dataset_names`
cache : boolean, optional
    If True, then cache data locally and use the cache on subsequent calls
data_home : string, optional
    The directory in which to cache data. By default, uses ~/seaborn-data/
kws : dict, optional
    Passed to pandas.read_csv
File:      c:\users\feyza\anaconda3\lib\site-packages\seaborn\utils.py
Type:      function


In [5]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [6]:
df.shape

(1035, 6)

In [7]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [8]:
df["mass"].mean()

2.6381605847953233

In [9]:
df["mass"].count()

513

In [10]:
df.min()

method            Astrometry
number                     1
orbital_period     0.0907063
mass                  0.0036
distance                1.35
year                    1989
dtype: object

In [11]:
df["mass"].min()

0.0036

In [12]:
df["mass"].max()

25.0

In [13]:
df["mass"].sum()

1353.37638

In [14]:
df["mass"].std()

3.8186166509616046

In [15]:
df["mass"].var()

14.58183312700122

In [17]:
df.describe() # Toplulaştırma Fonksiyonları

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [18]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [20]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# İleri Toplulaştırma İşlemleri(Aggregate,filter,transform,apply)

In [2]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                   'degisken1': [12,13,45,69,8,5],
                   'degisken2': [2,93,5,690,87,55]},
                   columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         12          2
1       B         13         93
2       C         45          5
3       A         69        690
4       B          8         87
5       C          5         55

In [8]:
#aggregate

In [4]:
df.groupby('gruplar').mean()

degisken1  degisken2
gruplar                      
A             40.5      346.0
B             10.5       90.0
C             25.0       30.0

In [7]:
df.groupby('gruplar').aggregate(['min',np.median,max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              12   40.5  69         2    346  690
B               8   10.5  13        87     90   93
C               5   25.0  45         5     30   55

In [9]:
df.groupby("gruplar").aggregate({"degisken1": "min","degisken2": "max"})

degisken1  degisken2
gruplar                      
A               12        690
B                8         93
C                5         55

In [1]:
#Filter

In [3]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                               'degisken1': [10,23,56,85,74,14],
                               'degisken2': [100,200,300,400,500,600]},
                               columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        200
2       C         56        300
3       A         85        400
4       B         74        500
5       C         14        600

In [8]:
def filter_func(x):
    return x["degisken1"].std() > 20

In [5]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A        53.033009  212.132034
B        36.062446  212.132034
C        29.698485  212.132034

In [10]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        200
2       C         56        300
3       A         85        400
4       B         74        500
5       C         14        600

In [11]:
#transform

In [13]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                               'degisken1': [10,23,56,85,74,14],
                               'degisken2': [100,200,300,400,500,600]},
                               columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        200
2       C         56        300
3       A         85        400
4       B         74        500
5       C         14        600

In [14]:
df["degisken1"]*9

0     90
1    207
2    504
3    765
4    666
5    126
Name: degisken1, dtype: int64

In [21]:
df_a = df.iloc[:,1:3]

In [23]:
df_a.transform(lambda x : x-x.mean()*x.std())

degisken1     degisken2
0 -1401.093361 -65379.004269
1 -1388.093361 -65279.004269
2 -1355.093361 -65179.004269
3 -1326.093361 -65079.004269
4 -1337.093361 -64979.004269
5 -1397.093361 -64879.004269

In [24]:
#apply

In [3]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
                   'degisken1': [10,23,56,85,74,14],
                   'degisken2': [100,200,300,400,500,600]},
                   columns = ['degisken1','degisken2'])
df

degisken1  degisken2
0         10        100
1         23        200
2         56        300
3         85        400
4         74        500
5         14        600

In [29]:
df.apply(np.sum)

degisken1     262
degisken2    2100
dtype: int64

In [31]:
df.apply(np.mean)

degisken1     43.666667
degisken2    350.000000
dtype: float64

In [4]:
import pandas as pd
df2 = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                               'degisken1': [10,23,56,85,74,14],
                               'degisken2': [100,200,300,400,500,600]},
                               columns = ['gruplar','degisken1','degisken2'])
df2

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        200
2       C         56        300
3       A         85        400
4       B         74        500
5       C         14        600

In [5]:
 df2.groupby("gruplar").apply(np.mean)

degisken1  degisken2
gruplar                      
A             47.5      250.0
B             48.5      350.0
C             35.0      450.0

# Pivot Tablolar

In [7]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [8]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [9]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [10]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [11]:
#pivot ile table

In [14]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [15]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [18]:
age = pd.cut(titanic["age"],[0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [20]:
titanic.pivot_table("survived",["sex","age"],"class")

class         First  Second  Third
sex    age                        
female 0.75     NaN     NaN   1.00
       1.00     NaN     NaN   1.00
       2.00     0.0     1.0   0.25
       3.00     NaN     1.0   0.00
       4.00     NaN     1.0   1.00
...             ...     ...    ...
male   70.00    0.0     0.0    NaN
       70.50    NaN     NaN   0.00
       71.00    0.0     NaN    NaN
       74.00    NaN     NaN   0.00
       80.00    1.0     NaN    NaN

[145 rows x 3 columns]

# Dosya Okuma

In [1]:
pwd


'C:\\Users\\FEYZA\\Desktop\\Veri Manipülasyonu'

In [2]:
import pandas as pd

In [5]:
pd.read_csv('reading_data/ornekcsv.csv',sep = ';')

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [7]:
pd.read_csv('reading_data/duz_metin.txt')

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [9]:
pd.read_excel('reading_data/ornekx.xlsx')

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0